# Start with the "official" Elixir build (this simplifies quite a bit here).
# This uses the "official" Erlang build (right now at 19.2) 
# on top of Debian jessie.
FROM elixir:1.3.4

MAINTAINER Your Name <name@your-domain.com>

ENV REFRESHED_AT 2016-12-31

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . /app

RUN mix deps.get

CMD ["bash"]
   